### PR TITLE
add SameSite support

### PR DESCRIPTION
**Pull request by lekoala**
also ignore lifetime if set to 0 (leave it to default)
+ use uppercases (it looks much better for SameSite rather than samesite)

### CODE REVIEW

**Comment by szepeviktor** [comment]
> use uppercases

MDN seconds it!
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by szepeviktor** [comment]
How about using arrays? https://github.com/middlewares/php-session/pull/11/files

**Comment by lekoala** [comment]
> How about using arrays? https://github.com/middlewares/php-session/pull/11/files

why not ;-)

**Comment by oscarotero** [comment]
Great. Thanks!

**Pull request merged**
